spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jwt_test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: jik
    password: jesusisking
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    database: h2