spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33060/jwt_study?serverTimezone=UTC&characterEncoding=UTF-8
    username: jik
    password: jesusisking

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

  security:
    jwt:
      header: Authorization
      secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
      blacklist:
        access-token: BlackList_AccessToken_

  redis:
    host: localhost
    port: 6379